import nodemailer from "nodemailer";

// ── Transport factory ─────────────────────────────────────────────────────────
const createTransporter = () => {
  const port = parseInt(process.env.SMTP_PORT || "587", 10);
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port,
    secure: port === 465,   // true for 465 (SSL), false for 587 (STARTTLS)
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
};

// ── HTML email builder ────────────────────────────────────────────────────────
const buildHtml = (summaryText) => {
  const bodyHtml = summaryText
    .split("\n")
    .filter((line) => line.trim())
    .map((line) => {
      // Section headings (numbered or markdown #)
      if (/^\d+\.\s/.test(line) || /^#+/.test(line)) {
        return `<h3 style="color:#1a3c5e;margin:20px 0 6px;">${line.replace(/^#+\s*/, "")}</h3>`;
      }
      // Bullet points
      if (/^[-•]\s/.test(line)) {
        return `<li style="margin-bottom:6px;">${line.replace(/^[-•]\s*/, "")}</li>`;
      }
      return `<p style="margin:8px 0;">${line}</p>`;
    })
    .join("\n");

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <title>Sales Executive Summary</title>
</head>
<body style="font-family:Arial,sans-serif;background:#f4f6f8;margin:0;padding:0;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f8;padding:32px 0;">
    <tr>
      <td align="center">
        <table width="640" cellpadding="0" cellspacing="0"
          style="background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.08);">

          <!-- Header -->
          <tr>
            <td style="background:#1a3c5e;padding:28px 36px;">
              <h1 style="color:#ffffff;margin:0;font-size:22px;letter-spacing:0.4px;">
                Sales Data Executive Summary
              </h1>
              <p style="color:#a8c4d8;margin:6px 0 0;font-size:13px;">
                Generated by Sales Insight Automator
              </p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:28px 36px;color:#333333;font-size:15px;line-height:1.75;">
              ${bodyHtml}
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#f0f4f8;padding:14px 36px;font-size:12px;color:#888888;text-align:center;">
              This report was automatically generated. Please do not reply to this email.
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `.trim();
};

// ── Public API ────────────────────────────────────────────────────────────────
export const sendSummaryEmail = async (recipientEmail, summaryText) => {
  const required = ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS"];
  const missing  = required.filter((v) => !process.env[v]);
  if (missing.length) {
    throw new Error(`Missing SMTP configuration: ${missing.join(", ")}`);
  }

  const transporter = createTransporter();
  // Verify SMTP connectivity before attempting to send
  await transporter.verify();

  await transporter.sendMail({
    from:    `"Sales Insight Automator" <${process.env.SMTP_USER}>`,
    to:      recipientEmail,
    subject: "Sales Data Executive Summary",
    text:    summaryText,
    html:    buildHtml(summaryText),
  });

  console.log(`[Email] Report sent to ${recipientEmail}.`);
};
